### ISSUE TITLE
Corresponding workflow's URL for Repo Action URL

### ISSUE THREAD

**Issue by 417-72KI** [rtCamp/action-slack-notify#10]
Currently the package sends **Repo Action URL** to Slack like below:
> https://github.com/${GITHUB_REPOSITORY}/actions

It shows history of workflows, and would be nice to show the corresponding workflow like this.
> https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}/checks

Example URL:
https://github.com/417-72KI/SSGH/commit/a3c27c06d820ae0d7a1947495c1da006f34867e2/checks

**Comment by mrrobot47** [comment]
Yes, that would be more helpful. Thanks for the suggestion, will add a patch for this.
