### ISSUE TITLE
Changing SLACK_CHANNEL value not working

### ISSUE THREAD

**Issue by jasf87** [rtCamp/action-slack-notify#108]
I'm updating the value of the SLACK_CHANNEL with a different value than the one configured in the webhook. It's a public channel. I'm still getting the message in the one configured with the webhook.

Is this the expected behaviour? And if that is the case, when will be useful to update the SLACK_CHANNEL value?

Thanks in advance and sorry if this is not an issue and just a miscomprehension of the readme file.

**Comment by yonat-ateam** [comment]
@jasf87 How did you solve this?
