### ISSUE TITLE
Keep failing at docker push

### ISSUE THREAD

**Issue by anatolygreen** [rtCamp/action-slack-notify#110]
What I have:
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: XXXX
          SLACK_COLOR: ${{ job.status }} 
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: 'MSG'
          SLACK_TITLE: 'title'
          SLACK_USERNAME: github-actions
          MSG_MINIMAL: actions url
          SLACK_WEBHOOK: ${{ secrets.SLACK_URL }}  

Expected: build and send Slack push
Got: 
Warning: Docker pull failed with exit code 1, back off 5.74 seconds before retry.
  /usr/bin/docker pull ghcr.io/rtcamp/action-slack-notify:v2.2.0
  Error response from daemon: received unexpected HTTP status: 503 Service Unavailable

**Comment by genieai-vikas** [comment]
I am facing the same issue. All of our builds started failing.

**Comment by mrrobot47** [comment]
GitHub packages is down. Please refer: https://github.com/rtCamp/action-slack-notify/issues/110
Due to this, the docker image of action `ghcr.io/rtcamp/action-slack-notify:v2.2.0` is failing and exiting in pull.

Once the above GitHub incident is resolved, it will start functioning normally.
