### ISSUE TITLE
on self-hosted runner : "cat: can't open '/github/workflow/event.json': No such file or directory"

### ISSUE THREAD

**Issue by phpdudimanche** [rtCamp/action-slack-notify#113]
This error when executed on a debian:buster 
Inside my runner, my dir si "/actions-runner/home/_actions/rtCamp/action-slack-notify/v2"

**Comment by phpdudimanche** [comment]
Also on host windows 10 / virtual box / vm host ubuntu:21.04 / container runner ubuntu:21.04

**Comment by anchangarkoselabs** [comment]
Same issue on Ubuntu 20.04

**Comment by mrrobot47** [comment]
This is a GitHub actions generic usage question. Please ask support for this on https://github.community/

**Comment by Frisch12** [comment]
This problem exists only with this action so "This is a generic usage question" is not really true. Why do you need to read this file in the first place?

**Comment by dthisner** [comment]
I would love a better solution or error for this, I am seeing this and I have no idea where to go from here.

**Comment by dthisner** [comment]
Seems that it does not work on self-hosted, I switched to ubuntu-latest and it worked fine
