### ISSUE TITLE
Error sending message: Error on message: 500 Internal Server Error

### ISSUE THREAD

**Issue by lucasrcezimbra** [rtCamp/action-slack-notify#115]
My pipelines started to fail today in this action with an error 500:

> Error sending message: Error on message: 500 Internal Server Error

Is anyone having the same error?

**Comment by dorain47** [comment]
Working for me.

**Comment by Mike-Sinistralis** [comment]
Happening to us as well. Seems intermittent.

**Comment by lucasrcezimbra** [comment]
Seems to be a problem in Slack: 

- https://status.slack.com/
- https://status.slack.com/2021-12/a17eae991fdc437d

Thank you.
