### ISSUE TITLE
WebHooks method is deprecated; update to GitHub Apps.

### ISSUE THREAD

**Issue by sarina** [rtCamp/action-slack-notify#119]
Hi,

The instructions say to use a webhook to configure:

> You can [generate a Slack incoming webhook token from here](https://slack.com/apps/A0F7XDUAZ-incoming-webhooks).

However this method is deprecated. This Action needs to be upgraded to use the suggested method.

<img width="910" alt="Screen Shot 2022-02-13 at 12 37 33" src="https://user-images.githubusercontent.com/1985317/153767369-949b8007-e2fb-4b89-803f-ed27ebd3fb3c.png">

Thanks!

**Comment by xrisaD** [comment]
Hello,
I could replace it with **chat.postMessage**. What do you think?

**Comment by titimoby** [comment]
I think it might have more impact than documentation.
I use action-slack-notify with a Slack App but the webhook you obtain is tied to a channel.
So the SLACK_CHANNEL parameter won't be used anymore.

Note: As I'm just starting to use this action, I may have missed some way to configure it.

**Comment by sarina** [comment]
Apologies for not adding what I did. I used a Slack app to do this integration. I guess I never even used this Action. https://github.com/openedx/.github/blob/master/.github/workflows/add-depr-ticket-to-depr-board.yml#L85-L92

**Comment by BrianInAz** [comment]
Would like to keep the existing deprecated functionality in place until Slack actually removes it. Slack apps should be default option moving fwd of course.

**Comment by BrianInAz** [comment]
> The instructions say to use a webhook to configure:
> 
> > You can [generate a Slack incoming webhook token from here](https://slack.com/apps/A0F7XDUAZ-incoming-webhooks).
> 
> However this method is deprecated. This Action needs to be upgraded to use the suggested method.

Agree that documentation should be updated to non-deprecated method. Slack Apps should be default moving forward. 

However, I would prefer to keep the existing deprecated functionality in place until Slack actually removes it.
