### ISSUE TITLE
[Feature request] Show run duration in Slack message

### ISSUE THREAD

**Issue by spencermehta** [rtCamp/action-slack-notify#121]
I'd like to include the run duration in the message sent to the slack channel.

**Comment by schmidtsonian** [comment]
+1

**Comment by josh803316** [comment]
+1

**Comment by pakhilov** [comment]
+1

**Comment by L0RD-ZER0** [comment]
Providing a run duration for a workflow would require that workflow to have a definite duration, i.e. have finished. If you want a transient duration, you may store the timestamps for the start of the run, and compare it against the time you send the message to obtain a relative duration.

As for supporting this behaviour baked into the action, we currently have no plans for doing that.
