### ISSUE TITLE
Error pulling image configuration 'ghcr.io/rtcamp/action-slack-notify:v2.2.0'

### ISSUE THREAD

**Issue by pedrofsantoscom** [rtCamp/action-slack-notify#126]
Related to https://github.com/rtCamp/action-slack-notify/issues/82
Our builds are failing now because it can't get the docker image.

<img width="1199" alt="image" src="https://user-images.githubusercontent.com/2325978/175023750-fdc4b97c-2ef9-4736-bdf0-0efca237d99a.png">

**Comment by ErlanBelekov** [comment]
+1

**Comment by mintunitish** [comment]
Facing the same issue!

**Comment by dhsathiya** [comment]
Taking a look. I was able to pull it on my system.

**Comment by kazuooooo** [comment]
Same here

**Comment by shahargl** [comment]
same here

**Comment by Jolg42** [comment]
Same here, examples
https://github.com/prisma/language-tools/actions
https://github.com/prisma/language-tools/runs/7002939957?check_suite_focus=true#step:2:45

https://www.githubstatus.com/history only shows a GitHub Pages incident at the moment
>[Incident with GitHub Pages](https://www.githubstatus.com/incidents/10vm6ctn52gx)
We are investigating reports of degraded performance for GitHub Pages.

**Comment by kamayla** [comment]
same here

**Comment by vladislavmarkovqs** [comment]
+ 1

**Comment by dhsathiya** [comment]
I have checked, and the issue is there.
As one of the GH services is impacted, it is possible that GH Actions and/or ghcr is also impacted.
I have also raised a ticket with GH for the same. :crossed_fingers:

**Comment by rsmartins78** [comment]
Same here, but just this action is failing.

**Comment by dhsathiya** [comment]
Confirmed - GH Packages are facing issues
>Update - GitHub Packages is experiencing degraded performance. We are continuing to investigate.
Jun 22, 12:43 UTC

![image](https://user-images.githubusercontent.com/26240780/175032488-1c98fbab-ff90-49bb-b871-7fdc41cc4e36.png)
Ref: https://www.githubstatus.com/incidents/10vm6ctn52gx
