### ISSUE TITLE
Dependabot PR fail with SLACK_WEBHOOK missing when it is set globally

### ISSUE THREAD

**Issue by speer-kinjo** [rtCamp/action-slack-notify#128]
Every time dependabot has a pr this action fails with 

`/usr/bin/docker run --name ghcriortcampactionslacknotifyv220_d25b8b --label 4cd98f --workdir /github/workspace --rm -e AWS_DEFAULT_REGION -e pythonLocation -e LD_LIBRARY_PATH -e SLACK_CHANNEL -e SLACK_COLOR -e SLACK_ICON -e SLACK_TITLE -e SLACK_USERNAME -e SLACK_WEBHOOK -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e GITHUB_STEP_SUMMARY -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e ACTIONS_ID_TOKEN_REQUEST_URL -e ACTIONS_ID_TOKEN_REQUEST_TOKEN -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/claim/claim":"/github/workspace" ghcr.io/rtcamp/action-slack-notify:v2.2.0
[ERROR] Secret `SLACK_WEBHOOK` is missing. Please add it to this action for proper execution.
Refer https://github.com/rtCamp/action-slack-notify for more information.`

However, it is set at the org level and if re-run it works ... suggestions

**Comment by nnnnat** [comment]
For anyone that may run into this issue in the future, dependabot can't access the action secrets even if they're set at the org level. You'll need to add the same `SLACK_WEBHOOK` secret for your org actions in the dependabot secrets section.
![dependabot-secret](https://user-images.githubusercontent.com/1135948/190246611-dfeed79c-6d99-47cb-a45d-f8e8ccfa10f6.png)

**Comment by L0RD-ZER0** [comment]
Thanks to @nnnnat for answering! Please set your credentials in the correct location and retry.
