### ISSUE TITLE
404 Not Found 

### ISSUE THREAD

**Issue by thiscodes4u** [rtCamp/action-slack-notify#129]
Over the last few days when running our builds, we've been running into errors that the package isn't found. Did something change?

/usr/bin/docker run --name ghcriortcampactionslacknotifyv220_9857b6 --label 4cd98f --workdir /github/workspace --rm -e SLACK_MSG -e SLACK_CHANNEL -e SLACK_ICON -e SLACK_TITLE -e SLACK_USERNAME -e SLACK_WEBHOOK -e SLACK_MESSAGE -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e GITHUB_STEP_SUMMARY -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/my-project":"/github/workspace" ghcr.io/rtcamp/action-slack-notify:v2.2.0

Error sending message: Error on message: 404 Not Found

**Comment by mustafasalfiti** [comment]
we have also the same problem

**Comment by sphuber** [comment]
Should the token include the `https://hooks.slack.com/services/` URL prefix, or just the string that follows it? I am getting the error
```
[ERROR] Secret `SLACK_WEBHOOK` is missing. Please add it to this action for proper execution.
```
but the secret definitely exists.

**Comment by mustafasalfiti** [comment]
https://hooks.slack.com/services/TOKEN it should be included in the string,

**Comment by someoddpilot** [comment]
UPDATE: I've followed the README and generated a new token. Everything seems to be working just fine. We'll see how long this lasts. Thank you @mustafasalfiti

**Comment by thiscodes4u** [comment]
I generated a new token following the steps in the README. Everything seems to be working just fine. Thank you @mustafasalfiti
