### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by FelipeUmpierre** [rtCamp/action-slack-notify#13]
Thanks for the great job on this action. I was checking the releases on this repo and I saw that the last one was make almost a year ago, any plans to create a new one to have the latest changes included?

**Comment by mrrobot47** [comment]
There have been quite a few changes after that release. I will create a new one tomorrow or latest by Monday. Till then if you want to use the latest changes you can temporarily use: `rtCamp/action-slack-notify@master`

**Comment by mrrobot47** [comment]
Closing. New tagging and releasing done: https://github.com/rtCamp/action-slack-notify/releases/tag/v2.0.0

**Comment by winzig** [comment]
@mrrobot47 Is there an explanation of what changed between 1.0 and 2.0? Thanks!
