### ISSUE TITLE
Assumes jq is installed for self hosted runners

### ISSUE THREAD

**Issue by jeremysf** [rtCamp/action-slack-notify#143]
Hello!

Thank you very much for this excellent action!

I am using a self hosted runner on Ubuntu 22.04.1 LTS, and jq does not come installed by default in the minimum distribution.

This causes the action to fail as it appears to assume jq is installed.

Probably worth at least documenting that dependency is needed for self hosted runners if not finding a way to address.

Thank you!

**Comment by mrrobot47** [comment]
Hey @jeremysf,

Can you please share the error that you are getting? 

This is a [Docker container based](https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action) GitHub action which does not require `jq` installed on the system where the action is being run. It already has [`jq` installed](https://github.com/rtCamp/action-slack-notify/blob/c753c78497b021971cf6540efe8c3a131e4b702f/Dockerfile#L29) in the container.
