### ISSUE TITLE
Error when trying to pull the action from Github actions 

### ISSUE THREAD

**Issue by mgm793** [rtCamp/action-slack-notify#147]
<img width="1300" alt="Screenshot 2023-03-15 at 16 13 04" src="https://user-images.githubusercontent.com/11296854/225354353-ad94f90c-f52f-4d3a-b83e-5d01316bbece.png">

**Comment by SaharAvr** [comment]
same(:

**Comment by dhsathiya** [comment]
It could be because of GitHub was facing issues with packages. The action should be working fine now.
https://www.githubstatus.com/incidents/ybnn77s3lyf8

Please re-open this issue if your problem persists.
Thanks.
