### ISSUE TITLE
Docker pull failed `v2.2.0`

### ISSUE THREAD

**Issue by piekstra** [rtCamp/action-slack-notify#148]
Just this morning we started seeing the following issue:

![image](https://user-images.githubusercontent.com/10527279/225442132-1738349c-7b8d-43b5-9ac9-d2aaad9eb126.png)

Accessing the link: https://ghcr.io/v2/rtcamp/action-slack-notify/manifests/v2.2.0
Returns the following response:
```
{"errors":[{"code":"UNAUTHORIZED","message":"authentication required"}]}
```

Is this project now behind a paywall of some sort?

## Context
We have a a GitHub Actions Workflow with the following step:
```
- name: Slack Notification
   uses: rtCamp/action-slack-notify@v2
```

**Comment by dhsathiya** [comment]
It could be because of GitHub was facing issues with packages. The action should be working fine now.
https://www.githubstatus.com/incidents/ybnn77s3lyf8

Please re-open this issue if your problem persists.
Thanks.
