### ISSUE TITLE
SLACK_MESSAGE: limit to 2000 characters

### ISSUE THREAD

**Issue by joacimguldskog** [rtCamp/action-slack-notify#156]
I can't send messages longer then ~2000+ characters it will truncate

https://stackoverflow.com/questions/75979046/slack-webhook-truncating-data-text

**Comment by L0RD-ZER0** [comment]
This is a slack limitation. The message in the attachment field can not go beyond 2000 characters. When it does, slack automatically truncates it with a ``...``. This is a limitation on Slack's end and not ours.
