### ISSUE TITLE
not running with Graviton processor

### ISSUE THREAD

**Issue by cb-anomitromunshi** [rtCamp/action-slack-notify#169]
recently we have changed to aws graviton and this action started breaking.
`exec /entrypoint.sh: exec format error` 
any help?

**Comment by L0RD-ZER0** [comment]
Can you provide some details on the CPU architecture? I know it's ARM64, but not sure on which version, say arm64/v7 or a64/v6. Further details on that would be appreciated.

**Comment by noamcohen97** [comment]
Seems like ARM64 docker image contains a x86 binary of bash.
This is because the base image is pinned to a specific manifest instead of to the index.
Created a #175 to address this issue

**Comment by L0RD-ZER0** [comment]
Updated the images, credits to @noamcohen97 for resolving this one!

**Comment by cb-anomitromunshi** [comment]
Thanks guys

**Comment by cb-anomitromunshi** [comment]
will this be available in the latest version?
           **rtCamp/action-slack-notify@v2.3.0**

**Comment by noamcohen97** [comment]
New docker images are already available with the old v2.3.0.
I don't know what's GitHub action image pull policy - but @L0RD-ZER0 maybe you should consider an image version bump to force re-pull?
