### ISSUE TITLE
Vault integration should use an AppRole rather than long-lived token

### ISSUE THREAD

**Issue by stevegore** [rtCamp/action-slack-notify#18]
It would be good to allow the use of Vault AppRoles to authenticate against vault, rather than tokens. Here's [an example of how this might be done](https://www.vaultproject.io/guides/identity/authentication/), albeit for Jenkins.

**Comment by mrrobot47** [comment]
Hey @stevegore, thanks for the suggestion. I agree that Vault AppRoles would be better to use instead of tokens. I will check more on AppRoles and will get action updated to accept AppRoles for vault interactions.

**Comment by RichiCoder1** [comment]
Pretty easy to implement, I do it for my stand-alone action: https://github.com/RichiCoder1/vault-action/blob/master/action.js#L31
Basically login w/ App Role creds to get a token, and continue as normal.

**Comment by mrrobot47** [comment]
@stevegore @RichiCoder1 if you are interested in this feature, please send a PR. Internally we dropped using vault a while back and that is why I have not worked in this feature.

I am keeping the existing vault support as it is for now. Closing this issue, if you guys are interested in creating ApprRole implementation PR, feel free to re-open this and send a PR against it. I will be more than happy to test and merge it.
