### ISSUE TITLE
Update on pull request

### ISSUE THREAD

**Issue by daniel-vc** [rtCamp/action-slack-notify#19]
Hi, would it be possible for this to update the message field when the event is on pull_request? Currently it comes back as null.

It would be also helpful if it came back with success or not if the current job was succesful etc

Thank you

**Comment by nicoitraxar** [comment]
to notify according to outcome you could do the following:
`    - name: Slack Notify
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@v2.0.1
        env:
         SLACK_MESSAGE: 'all cool! :rocket:'
         SLACK_TITLE: finished ok
         SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      - name: Slack Notify
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2.0.1
        env:
         SLACK_TITLE: Failed task
         SLACK_MESSAGE: 'Failed! :cry:'
         SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}`

**Comment by daniel-vc** [comment]
Thanks very much for the reply @nicoitraxar - will give that a try 👍

**Comment by mrrobot47** [comment]
@daniel-vc as this issue seems to be resolved. I am closing it.
For more details on env variables, you can referer: https://github.com/rtCamp/action-slack-notify#environment-variables
