### ISSUE TITLE
Release a new stable version with nodejs update

### ISSUE THREAD

**Issue by jylenhofdecat** [rtCamp/action-slack-notify#201]
Hi,

It seems you already merge on master branch the necessary bump to avoid the warning about using old nodejs 16
https://github.com/rtCamp/action-slack-notify/commit/07e445259dcae1b892dfebcaec924ce75b484902

For the record the information on github :
https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
https://github.blog/changelog/2024-09-25-end-of-life-for-actions-node16/

So can you release a new stable version with this commit in ?
For my enterprise use, we will use the commit hash to avoid the warning but an update is welcome.

Regards,

**Comment by mrrobot47** [comment]
https://github.com/rtCamp/action-slack-notify/releases/tag/v2.3.1

**Comment by mrrobot47** [comment]
Released in the stable `v2`.
