### ISSUE TITLE
Builds breaking with unable to find version v2

### ISSUE THREAD

**Issue by kedarkekan** [rtCamp/action-slack-notify#202]
![Screenshot 2024-10-17 at 6 39 22 PM](https://github.com/user-attachments/assets/b1f85cdf-aed1-4c9c-b174-50a8af25a58c)

**Comment by CarolineLavergne1** [comment]
same error on my side

**Comment by shideneyu** [comment]
same error on my side

**Comment by meteorlxy** [comment]
same here

**Comment by pat-hus** [comment]
same

**Comment by kedarkekan** [comment]
Workaround, update package to
```
rtCamp/action-slack-notify@v2.3.1
```

**Comment by mrrobot47** [comment]
It has been fixed. Thanks for reporting the issue.
```
rtCamp/action-slack-notify@v2
```
Should work now as usual with the latest v2 update.
