### ISSUE TITLE
No support for windows-latest

### ISSUE THREAD

**Issue by ArchieCoder** [rtCamp/action-slack-notify#23]
Hi,

Until the action is not supported on windows-latest, it should be written in the documentation that it runs only on ubuntu.

Thanks

**Comment by AlexShemeshWix** [comment]
Its not supporting windows.

**Comment by L0RD-ZER0** [comment]
In a similar fashion to #22, GitHub runners for Windows do not support container based actions, and we don't plan on shipping native Windows executables for the action. Instead, consider breaking your workflow into multiple steps and using the action from a different workflow step running on a Linux runner, similar to resolution suggested by @thefex in #22.
