### ISSUE TITLE
Building every time

### ISSUE THREAD

**Issue by andreyvital** [rtCamp/action-slack-notify#27]
Is there a way not to build every time? it's consuming 1 minute for every action I run. This has impact in my billing as I run a lot of actions per month

**Comment by dhsathiya** [comment]
@mrrobot47 I think we should build a Docker image.

**Comment by andreyvital** [comment]
That'd help!

**Comment by mrrobot47** [comment]
This has already been covered in this issue: https://github.com/rtCamp/action-slack-notify/issues/16#issuecomment-614026575

Use: `rtCamp/action-slack-notify@master` that has the docker image usage inside it.

Also, there is a planned release on Monday, which will release a new stable tag with the docker image usage. But, you can keep using the `@master` tag as that will always have the latest stable release.

**Comment by andreyvital** [comment]
Perfect @mrrobot47. Now it takes ~4s here haha. Thanks! Maybe update the README so other people know?

Thanks!
