### ISSUE TITLE
The action url is incorrect when pull request

### ISSUE THREAD

**Issue by weipengzhu** [rtCamp/action-slack-notify#30]
Event: pull_request
Actions URL: https://github.com/weipengzhu/testaction/commit/7f91b6abdebd55ef0e50ce12235fbfde024b6869/checks

**Comment by mrrobot47** [comment]
Thanks for reporting the issue. It has been fixed.

As this has not yet been released, you will have to use `@master` to get the fix.
Update your action to have the following uses:

```yml
      uses: rtCamp/action-slack-notify@master
```

**Comment by weipengzhu** [comment]
Good Job！
