### ISSUE TITLE
mentioning someone? (feature request)

### ISSUE THREAD

**Issue by sebastiangug** [rtCamp/action-slack-notify#35]
Would it be overly complex to add the option to mention someone? sadly bots don't trigger notifications for keywords so the only option would be to manually notify users --- even using the member id would be super helpful.

**Comment by 0x2b3bfa0** [comment]
@sebastiangug, you can mention people by specifying their identifier between `<@` and `>`

<details>
<summary><b>Source: https://api.slack.com/reference/surfaces/formatting#mentioning-users</b></summary>
<blockquote>
<h3>Mentioning users</h3>
<p>A mention is a special type of reference that will provide a link to the mentioned user's profile in the published text.</p>
<p>If the mention is included in an app-published message, the mentioned user will also be notified about the reference. The help center page for mentions describes what that notification process looks like.</p>
<p>To mention a user in app-published text, you need to provide their user ID in the following syntax: <pre>Hey <@U024BE7LH>, thanks for submitting your report.</pre></p>
<p>Your app can get this user ID from an interaction request payload, from the Event API payload sent when one of the event types occurs, or by looking them up via the users.list Web API using another unique piece of information you have about them (such as their email address).</p>
<p>You can also manually retrieve a specific user's ID by clicking on the overflow button in their Slack profile, and choosing the Copy member ID option, as shown in the screenshot.</p>
<img alt="Menu showing user ID in Slack profile" src="https://a.slack-edge.com/80588/img/api/user_id_manual_lookup.png" width="240" />
<p>When text containing the user-mention syntax is published by an app, the ID will be automatically converted to show the display name of the user.</p>
<blockquote>
<p>If you're retrieving messages, you can use the users.info Web API method to lookup by user ID and find out other relevant information, such as their display name.</p>
</blockquote>
</details>

**Comment by 0x2b3bfa0** [comment]
@mrrobot47, probably, this issue should be closed soon.

**Comment by mrrobot47** [comment]
Closing this issue as solution provided by @0x2b3bfa0 is sufficient.
