### ISSUE TITLE
Passing secrets in YAML format?

### ISSUE THREAD

**Issue by winzig** [rtCamp/action-slack-notify#4]
I'm using a .yml workflow file, and trying to use this action. I am having trouble understanding how to pass the slack webhook url in YAML format, since it seems to be passed in separately from the env variables?

**Comment by marcelobfonseca** [comment]
@winzig I'm having errors trying to write 
```
workflow "Slack Notification Demo" {
  resolves = ["Slack Notification"]
  on = "push"
}

action "Slack Notification" {
  uses = "rtCamp/action-slack-notify@master"
  secrets = ["SLACK_WEBHOOK"]
}

```
to yaml. Can you share your code?
