### ISSUE TITLE
Invalid Action URL

### ISSUE THREAD

**Issue by jarretmoses** [rtCamp/action-slack-notify#40]
I recently started noticing that the Action URL generated is pointing to a dead link. Looking at the source code it seems to use the `GITHUB_SHA` env variable to dynamically generate the link. However, this SHA seems to be incorrect. If I update the link in my browser to use the commit sha of the head of my branch the link correctly works again. For example in a Github Action this is `${{ github.event.pull_request.head.sha }}`.  This may not be a issue exactly with this tool but perhaps it would be beneficial to add a override env variable to allow passing in this sha. I've tried doing this already but it doesn't seem like I can override `GITHUB_SHA` as is.

**Comment by jarretmoses** [comment]
Follow up it seems this out of sync issue is specific to `pull_request` action events which is apparently expected but even further makes me think this should be customizable for this ACtion

**Comment by mrrobot47** [comment]
Closing as this has been fixed and will be released soon in a stable version.
For now use tag `@master` to fix this.

Please check https://github.com/rtCamp/action-slack-notify/issues/30 for more details.
