### ISSUE TITLE
Request for support to add attachment env var

### ISSUE THREAD

**Issue by hiqqs** [rtCamp/action-slack-notify#43]
Hi, it would be awesome if we could add an attachment env var to support adding a file such as html report.

i've tried using some of the other github actions that have this but they don't seem to work and i've had best success with this one.

**Comment by mrrobot47** [comment]
Hey @johnhiggs :wave: 

Thanks for submitting a feature request.

Adding file attachments is not directly possible via incoming webhooks which is what we use primarily in this action.
I will still look into the feasibility of integrating https://api.slack.com/methods/files.upload in this action and will get back to you on this later :slightly_smiling_face:

**Comment by lemiorhan** [comment]
Hi, firstly I would like to thank you for providing such a great tool for us.

Is there any progress on this topic so far? We also build markdown/html reports and send to slack. After 2048 characters the content is truncated. It would be great to have attachment support to use.
