### ISSUE TITLE
Feature request - customize github actor

### ISSUE THREAD

**Issue by ZacSweers** [rtCamp/action-slack-notify#49]
Right now the actor is always who triggered the action, but it would be nice if this could be customized (i.e. manually pick the PR author even if it is triggered from someone else merging it, etc). Related - an option to hide this if it's not relevant

**Comment by ross-kortx** [comment]
👍 minor but good for cron scheduled jobs

**Comment by mrrobot47** [comment]
This has been fixed in https://github.com/rtCamp/action-slack-notify/releases/tag/v2.1.1
You can use env var: `SLACK_MSG_AUTHOR` to specify GitHub username for the message.

Please use `uses: rtCamp/action-slack-notify@v2` to use this feature.
