### ISSUE TITLE
Docker hub toomanyrequest error

### ISSUE THREAD

**Issue by kldavis4** [rtCamp/action-slack-notify#52]
Seeing this error when using this action on a self-hosted runner (`uses: rtCamp/action-slack-notify@v2.0.2`)

```
Pull down action image 'rtcamp/action-slack-notify:v2.0.2'
  /usr/bin/docker pull rtcamp/action-slack-notify:v2.0.2
  Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
  Warning: Docker pull failed with exit code 1, back off 5.965 seconds before retry.
  /usr/bin/docker pull rtcamp/action-slack-notify:v2.0.2
  Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
  Warning: Docker pull failed with exit code 1, back off 8.716 seconds before retry.
  /usr/bin/docker pull rtcamp/action-slack-notify:v2.0.2
  Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```

Is there a different public repository that can be used?

**Comment by mrrobot47** [comment]
Were you trying/running a lot of actions on the self-hosted runner?

>https://www.docker.com/increase-rate-limit
>Temporary full enforcement window (100 per six hours for unauthenticated requests, 200 per six hours for free accounts): November 5, 12pm-3pm Pacific Time.

The rate limit during the time you created issue was 100 pulls/6hrs for anonymous users.
Note that this limit is per IP, so it seems like your self-hosted runners IP pulled more images than the limit.

Try running the action again, it should work now, the rate limits _for now_ have also been relaxed to 2500 pulls/6hrs.

In case this issue persits and is experienced more frequently by multiple users, we will look into other options.

**Comment by kldavis4** [comment]
Thanks for your response! Those specific self-hosted runners were not running a significant number of actions during that time period. They are running in EC2 behind a nat gateway, so if there were other hosts behind that same nat ip making a lot of pulls that might have caused it.

**Comment by mrrobot47** [comment]
>if there were other hosts behind that same nat ip making a lot of pulls that might have caused it.
Yes, that's highly likely. 

Also, the issue you faced can occur in such scenarios once the docker hub rate limits are completely lowered to the final state.

So, will be evaluating other public registeries for this action. [GitHub container registry](https://github.blog/2020-09-01-introducing-github-container-registry/) looks like a good alternative.

**Comment by kldavis4** [comment]
I think also [this](https://github.com/rtCamp/action-slack-notify/blob/master/action.yml#L6) limits our ability to specify an alternate repository

**Comment by mrrobot47** [comment]
That's fine. I was not considering adding anither alternate registry.

What I meant by:

>So, will be evaluating other public registeries for this action

Was that if another public registry is better and does not have limitations with public images, which seems like the case with GitHub container registry. We will move away from docker.io completely to that registry and do patch release in the action with the change in `action.yml`.

**Comment by mrrobot47** [comment]
This has been fixed in https://github.com/rtCamp/action-slack-notify/releases/tag/v2.1.1
Please use `uses: rtCamp/action-slack-notify@v2` for the latest changes.

**Comment by kldavis4** [comment]
great - ty @mrrobot47
