### ISSUE TITLE
Request to make actionUri configurable

### ISSUE THREAD

**Issue by rajiv-webill** [rtCamp/action-slack-notify#56]
Hi,

I wanted to know if its possible to make the actionUri configurable or atleast point to the commit instead of its checks?
Maybe creating an env variable to append the /checks onto the action URI

Kind regards,
Rajiv

**Comment by mrrobot47** [comment]
Hey, @rajiv-webill thanks for the feature request.

Instead of making actionUri configurable, I am planning on adding `Commit` field in the slack notification besides the `Actions URL` field so that you can view commit details as well as Actions URL.

**Comment by mrrobot47** [comment]
This has been released in https://github.com/rtCamp/action-slack-notify/releases/tag/v2.1.2

Please use `uses: rtCamp/action-slack-notify@v2` to use this feature if you are not already using `@v2` tag for the action.

**Comment by rajiv-webill** [comment]
Thanks very much @mrrobot47 much appreciated
