### ISSUE TITLE
about line break and hyper link 

### ISSUE THREAD

**Issue by soochun-deali** [rtCamp/action-slack-notify#57]
First of all, thank you so much for your plugin. 
It's really good :)

By the way, I want some requests. It might be silly requests.

1. `line break` with message or title
I tried with below. But I can not insert line break.
- Hello\nWorld  => `Hello\nWorld`
- Hello\nWorld  => `Hello\nWorld`
- Hello%0AWorld => `Hello%0AWorld`

2. make `Action URL link` short  like below
I think if you make a hyperlink, it will look more readable

![스크린샷 2020-11-25 오후 6 48 27](https://user-images.githubusercontent.com/55835522/100210940-e0c69f80-2f4e-11eb-8012-35f71b0941da.png)

**Comment by mrrobot47** [comment]
Hey @soochun-deali how did you setup the env var? Can you share your workflow file?

Using the following should work:
```yml
SLACK_MESSAGE: "Hello\nWorld"
```

**Comment by soochun-deali** [comment]
Thank you it works.

I used with single quote `'`

**Comment by mrrobot47** [comment]
A fix for feature request 2 has been merged. It will be released on/by Monday.

**Comment by mrrobot47** [comment]
>make Action URL link short

This has been released in https://github.com/rtCamp/action-slack-notify/releases/tag/v2.1.2

Please use `uses: rtCamp/action-slack-notify@v2` to use this feature if you are not already using `@v2` tag for the action.
