### ISSUE TITLE
Collapsing Actions URL to a link

### ISSUE THREAD

**Issue by aramir** [rtCamp/action-slack-notify#58]
UX improvement request: to decrease the verbosity of the message it would be great to have an option to send "Actions URL"  a "link" vs the full blown URL text, with an ability to customize the link's text. 

So, something like this:

![image](https://user-images.githubusercontent.com/2984000/100292905-c84a8b00-2f36-11eb-867f-0c4cfbe6d097.png)

**Comment by mrrobot47** [comment]
Thanks for bringing this to our attention. We will be fixing this soon :slightly_smiling_face:

**Comment by mrrobot47** [comment]
A fix for this has been merged. It will be released on/by Monday.
The action run link will have the [workflow name](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#name) as placeholder text. To customize it you can update your workflow name.

**Comment by mrrobot47** [comment]
A fix for this has been merged. It will be released on/by Monday.
The action run link will have the [workflow name](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#name) as placeholder text. To customize it you can update your workflow name.

**Comment by mrrobot47** [comment]
This has been released in https://github.com/rtCamp/action-slack-notify/releases/tag/v2.1.2

Please use `uses: rtCamp/action-slack-notify@v2` to use this feature if you are not already using `@v2` tag for the action.
