### ISSUE TITLE
Env variables in slack message

### ISSUE THREAD

**Issue by outrunthewolf** [rtCamp/action-slack-notify#7]
I'm having trouble getting env variables into the slack message like so:

```
SLACK_MESSAGE: "Staging deployment complete: $GITHUB_SHA ${GITHUB_SHA}"
```

None of these seem to work. Am I doing something wrong?

**Comment by tmhuysen** [comment]
>SLACK_MESSAGE: Staging deployment complete: ${{ env.GITHUB_SHA }} 

or

>SLACK_MESSAGE: Staging deployment complete: $env.GITHUB_SHA
 
should work.

**Comment by juanitoddd** [comment]
Hello, thanks for the awesome work.
Is there a way to access the commit message inside this action ?

**Comment by mrrobot47** [comment]
@outrunthewolf the following will work if you want to get the GitHub SHA in message:

```yml
      env:
        SLACK_MESSAGE: Staging deployment complete: ${{ github.sha }}
```

For other variables and context details that you can use in GitHub Actions env variables please go through: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/contexts-and-expression-syntax-for-github-actions#about-context-and-expressions

You will get all the variables you can use in the [github-context table.](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/contexts-and-expression-syntax-for-github-actions#github-context)

**Comment by mrrobot47** [comment]
Hey @juanitoddd, as mentioned in the above comment, you can check out all the variables in the [github-context table.](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/contexts-and-expression-syntax-for-github-actions#github-context)

The most powerful of those is `github.event`, which has loads of data that can be accessed. To know the exact data in it you can check this payload example: https://developer.github.com/v3/activity/events/types/#webhook-payload-example
Or on your own create a test GitHub action and simply run `cat $GITHUB_EVENT_PATH` to get the complete json payload of data available.

So, if you want to access commit message, you can use: `${{ github.event.head_commit.message }}`
```yml
      env:
        SLACK_MESSAGE: "Some text before commit message. Commit Message: ${{ github.event.head_commit.message }}"
```
