### ISSUE TITLE
Remove username and avatar when Github event is 'schedule'

### ISSUE THREAD

**Issue by gagle** [rtCamp/action-slack-notify#75]
Currently, when you set a workflow that runs automatically based on a schedule event, the username that appears in the notification is the one from the user that commited this change. This is undesirable and I would like to remove it.

**Comment by david-gourde** [comment]
I also do not want to have the github user in the notification, as it doesn't have anything to do with the topic, and is detrimental. I don't want to see who sent the commit that broke something, I just want to see what's broken and have some info about it to fix it. The avatar and github username should be "excludable" by not adding it to the "MSG_MINIMAL" whitelist, like the other fields.
