### ISSUE TITLE
color is not set when using ${{job.status}}

### ISSUE THREAD

**Issue by Morriz** [rtCamp/action-slack-notify#77]
Hi, when following the docs that say

`You can pass ${{job.status}} for automatic coloring or an RGB value like #efefef which would change color on left side vertical line of Slack message.`

No color is used.

We use
```
SLACK_COLOR: ${{ job.status }}
SLACK_MESSAGE: Workflow ${{ job.status }}
```
And see the message showing "Workflow success", so `job.status` is set to "success".

**Comment by mrrobot47** [comment]
This feature was recently merged and is yet to be released. It will be released today mostly. After that, this should work.

**Comment by mrrobot47** [comment]
This has been fixed in https://github.com/rtCamp/action-slack-notify/releases/tag/v2.1.3 and released.
Please use `uses: rtCamp/action-slack-notify@v2` (if you are not already using `@v2` tag) for the latest changes.
