### ISSUE TITLE
Env variable for icon_emoji

### ISSUE THREAD

**Issue by bayssmekanique** [rtCamp/action-slack-notify#8]
Currently the package only supports using an icon with a URL, but it would be nice to be able to use built in Slack Emoji's using the `icon_emoji` property as an alternative.

**Comment by PaulSearcy** [comment]
@mrrobot47

_Disclaimer: I don't really know Go, just grokking based on basic syntax_ 

Looking at `main.go` file 

 ```go
const (
	EnvSlackWebhook  = "SLACK_WEBHOOK"
	EnvSlackIcon     = "SLACK_ICON"
	EnvSlackChannel  = "SLACK_CHANNEL"
	EnvSlackTitle    = "SLACK_TITLE"
	EnvSlackMessage  = "SLACK_MESSAGE"
	EnvSlackColor    = "SLACK_COLOR"
	EnvSlackUserName = "SLACK_USERNAME"
	EnvGithubActor   = "GITHUB_ACTOR"
	EnvSiteName      = "SITE_NAME"
	EnvHostName      = "HOST_NAME"
	EnvDepolyPath    = "DEPLOY_PATH"
)

type Webhook struct {
	Text        string       `json:"text,omitempty"`
	UserName    string       `json:"username,omitempty"`
	IconURL     string       `json:"icon_url,omitempty"`
	IconEmoji   string       `json:"icon_emoji,omitempty"`
	Channel     string       `json:"channel,omitempty"`
	UnfurlLinks bool         `json:"unfurl_links"`
	Attachments []Attachment `json:"attachments,omitmepty"`
}
```

It seems you've already got the `Webhook` type set up for `IconEmoji`.


Later on 

```go
	msg := Webhook{
		UserName: os.Getenv(EnvSlackUserName),
		IconURL:  os.Getenv(EnvSlackIcon),
		Channel:  os.Getenv(EnvSlackChannel),
		Attachments: []Attachment{
			{
				Fallback: envOr(EnvSlackMessage, "GITHUB_ACTION=" + os.Getenv("GITHUB_ACTION") + " \n GITHUB_ACTOR=" + os.Getenv("GITHUB_ACTOR") + " \n GITHUB_EVENT_NAME=" + os.Getenv("GITHUB_EVENT_NAME") + " \n GITHUB_REF=" + os.Getenv("GITHUB_REF") + " \n GITHUB_REPOSITORY=" + os.Getenv("GITHUB_REPOSITORY") + " \n GITHUB_WORKFLOW=" + os.Getenv("GITHUB_WORKFLOW")),
				Color:      envOr(EnvSlackColor, "good"),
				AuthorName: envOr(EnvGithubActor, ""),
				AuthorLink: "http://github.com/" + os.Getenv(EnvGithubActor),
				AuthorIcon: "http://github.com/" + os.Getenv(EnvGithubActor) + ".png?size=32",
				Footer: "<https://github.com/rtCamp/github-actions-library|Powered By rtCamp's GitHub Actions Library>",
				Fields: fields,
			},
		},
	}
```

Is where you instantiate the type into the variable `msg` which gets later on passed into the `send` function. ( Talking this out to make sure I'm not missing something) 

Would it be easy enough to just add another Env variable like `EnvSlackIconEmoji`.
Then  when `Webhook` is instantiated to `msg` add the property `IconEmoji`, rather than omitting it, and set the value via `os.Getenv(EnvSlackIconEmoji)`?

**Comment by mrrobot47** [comment]
@PaulSearcy yes, it should work ideally as you described. As you have already looked into this issue and have come so far, it would be great if you try it out and send a PR for this.

**Comment by PaulSearcy** [comment]
@mrrobot47  perfect. 

I actually already forked the repo and got it working for my use case. 

Though I stripped out the footer in the same commit that I implemented the changes. 

I'll have to take a second to split my changes into two commits. One for the PR and the second so I can continue to use the wonderful action you guys created without the footer tag.
