### ISSUE TITLE
Not supporting enterprise server

### ISSUE THREAD

**Issue by palloberg** [rtCamp/action-slack-notify#85]
The hostname `github.com` appears to be hard-coded into the links for the Actions URL and Commit hash, making the action unsuitable for users on GitHub Enterprise Server where the host is not `github.com`. The `GITHUB_SERVER_URL` environment variable should be used instead (see https://docs.github.com/en/actions/reference/environment-variables)

**Comment by mrrobot47** [comment]
Noted. Thanks for creating this issue, it will be fixed by next release.

**Comment by kotyara85** [comment]
@palloberg I opened this PR to address - https://github.com/rtCamp/action-slack-notify/pull/87/commits

**Comment by mrrobot47** [comment]
This has been released in https://github.com/rtCamp/action-slack-notify/releases/tag/v2.2.0
You can use `@v2` tag of this action to use this feature.

@kotyara85 @palloberg please test this and let me know if this is working as expected. I could not test it on GitHub Enterprise server.
