### ISSUE TITLE
Add GITHUB_URL

### ISSUE THREAD

**Issue by kotyara85** [rtCamp/action-slack-notify#86]
Many companies are using github enterprices, so github.com url won't work for them

**Comment by mrrobot47** [comment]
Closing as duplicate of https://github.com/rtCamp/action-slack-notify/issues/85

Thanks for the PR https://github.com/rtCamp/action-slack-notify/pull/87, we will be reviewing it and testing it soon.

**Comment by kotyara85** [comment]
Thanks, I didn’t pay attention on 85, lol
