### ISSUE TITLE
Weird Error cat: can't open '/github/workspace/.github/hosts.yml': No such file or directory 

### ISSUE THREAD

**Issue by eitam-ring** [rtCamp/action-slack-notify#9]
Why am I receiving can't open '/github/workspace/.github/hosts.yml'?

**Comment by freekmurze** [comment]
I'm getting the same error.

**Comment by denitsa-cm** [comment]
Same here

**Comment by mrrobot47** [comment]
Thanks for reporting the issue :slightly_smiling_face: 
Have added a fix.
