### ISSUE TITLE
User mention

### ISSUE THREAD

**Issue by sta-szek** [rtCamp/action-slack-notify#93]
Hi guys,

is it possible somehow to mention user in slack that is responsible for workflow invocation?
I tried to use `SLACK_MESSAGE: ":bearded_person: Test notification: ghcom-actions/rtcamp-action-slack-notify@v2\n @${{ github.actor }} :rocket: "`

but the message looks like that:
![Screenshot 2021-05-19 at 16 43 47](https://user-images.githubusercontent.com/6240704/118833000-62c1d080-b8c1-11eb-8f19-698d30589c6f.png)

**Comment by mrrobot47** [comment]
You can mention a user using slack mention. Ref: https://api.slack.com/reference/surfaces/formatting#mentioning-users

The syntax for it will be something like:
```
SLACK_MESSAGE: ":bearded_person: Test notification: ghcom-actions/rtcamp-action-slack-notify@v2\n <@SLACKUSERID> :rocket: "
```

Where you replace the `SLACKUSERID` with the user id you get from the user's slack profile as shown in this [image](https://a.slack-edge.com/80588/img/api/user_id_manual_lookup.png).

**Comment by mrrobot47** [comment]
Unfortunately, you will need the user id of the person you want to tag, and the dynamic behaviour that you are trying to achieve via `@${{ github.actor }}` will not be possible.

**Comment by yongzhang** [comment]
> Unfortunately, you will need the user id of the person you want to tag, and the dynamic behaviour that you are trying to achieve via `@${{ github.actor }}` will not be possible.

Is it possible to dynamically tag the user below? Would it be great if it has the feature.

![image](https://user-images.githubusercontent.com/15604715/123064107-8fc54e00-d440-11eb-80ae-1e460e854b32.png)
