### ISSUE TITLE
Support for Slack app tokens

### ISSUE THREAD

**Issue by FalconerTC** [rtCamp/action-slack-notify#96]
Slack app webhooks only allow you to post to a single channel. The [incoming webhooks](https://renttherunway.slack.com/apps/A0F7XDUAZ-incoming-webhooks) app let's you send to any channel, but it's considered legacy. Using tokens with a Slack app would let you post to multiple channels with the same token. There are a couple of different Github slack notifying apps that support this

**Comment by titimoby** [comment]
I don't know if support has been officially released but I just made a sample repo to check and it seems to be working (except SLACK_ICON and SLACK_ICON_EMOJI that doesn't work apparently)

**Comment by ajay-ca** [comment]
@titimoby  Could you tell me how did you do that?? I mean in which parameter did you use to put that token??
