### ISSUE TITLE
`SLACK_LINK_NAMES` not working

### ISSUE THREAD

**Issue by ndom91** [rtCamp/action-slack-notify#98]
Hey so i saw recently this new env var was added to automention usernames in slack, but I can't seem to get it to work.

I have a few variations, none of which work.

I set `SLACK_LINK_NAMES: true`.

Then, in one `SLACK_MESSAGE` I have, `PR by <@{{ github.action}}>` which doesn't get linked, just prints the text `PR by @ndom91`, for example.

In another `SLACK_MESSAGE` I have the username explicitly written out, i.e. `PR by @engineering-team` which also doesn't seem to get linked.

Am I missing something?

**Comment by mrrobot47** [comment]
Please refer: https://github.com/rtCamp/action-slack-notify/issues/93#issuecomment-854547992

**Comment by mrrobot47** [comment]
In general with `SLACK_LINK_NAMES: true`, you will be able to use `@here`, `@channel` etc. For tagging a user, you will have to refer the comment mentioned above.

**Comment by ndom91** [comment]
Yeah I thought SLACK_LINK_NAMES went around having to get the userId. No? 

Then quick question, I know its not related to this plugin per se, but do slack groups/teams have ids? Or just users?

**Comment by mrrobot47** [comment]
Groups/teams also have ids, check this: https://stackoverflow.com/a/44883343/13402747

**Comment by tranduchuy** [comment]
I need to know the user id from github.event so I get automatically at workflow config file, do you know @mrrobot47 ?
